[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.coverage]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
